program: main.py
method: bayes
metric:
  name: ood/auroc
  goal: maximize
parameters:
  model.training.learning_rate:
    min: 0.00001
    max: 0.0001
  model.training.batch_size:
    values: [16, 32, 64]
  model.training.weight_decay:
    values: [0.0, 0.01, 0.1]
  experiment.seed:
    values: [42, 123, 2024]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
